### ISSUE TITLE
多人用同一个BOT，提问都在同一个chat里！！！

### ISSUE THREAD

**Issue by kitkw** [yym68686/ChatGPT-Bing-Telegram-Bot#8]
多人用同一个BOT，提问都在同一个chat里。如果是同时提问的话，也只能回答到先提出的一边。
但我同时使用网页版就可以跟TG不在同一个chat，不冲突。
有没有办法解决或者多个BOT绑定一个GPT??避免多人在同一个chat.

**Comment by yym68686** [comment]
开发时间有限，已经加入到待实现的功能列表里面了。如果有能力的话欢迎 pr 👏。

**Comment by ly-img** [comment]
replit出错 请问这么解决

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.11 requires packaging<21.0,>=20.4, but you have packaging 23.0 which is incompatible.

**Comment by yym68686** [comment]
> replit出错 请问这么解决
> 
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. poetry 1.1.11 requires packaging<21.0,>=20.4, but you have packaging 23.0 which is incompatible.

已经修复了，重新部署一下试试。

**Comment by yym68686** [comment]
> 多人用同一个BOT，提问都在同一个chat里。如果是同时提问的话，也只能回答到先提出的一边。 但我同时使用网页版就可以跟TG不在同一个chat，不冲突。 有没有办法解决或者多个BOT绑定一个GPT??避免多人在同一个chat.

现在已经支持多人不同对话啦，欢迎试用！👏
